train_dir: "/data/datasets/simple/train"
val_dir: "/data/datasets/simple/dev"

languages: ['english', 'french', 'german', 'russian', 'spanish'] # in alphanumeric order

audio_length_s: 10
len_segment_ms: 20
input_shape: [129, 500, 1]
color_mode: "grayscale"
audio_feature: "spectrogram"
seed: 123

zero_center_img: False
remap_img: None

batch_size: 32
learning_rate: 0.001
num_epochs: 20

model: "eff"
