# Dataset
# languages: ["english","farsi","french","german","mandarin","spanish","polish","russian"]
languages: ["english", "german"]
train_dir: "test/data/"
val_dir: "test/data/"
augment: True

# Audio
audio_length_s: 5
sample_rate: 16000
feature_type: "stft"    # one of: mel, stft, fbank
feature_nu: 256

# Training
batch_size: 32
learning_rate: 0.001
num_epochs: 20
model: "eff"            # name the file in src/models

# Other
show_progress: True
