
languages: ["english", "french", "german", "spanish"]

# Training
train_dir: "/data/datasets/logfbank/large4lang/train"
val_dir: "/data/datasets/logfbank/large4lang/dev"
zero_center_img: False
remap_img: None
input_shape: [40, 500, 1]
color_mode: "grayscale"
seed: 123
batch_size: 512
learning_rate: 0.001
num_epochs: 20
model: "attRnn"

